export const AUDIO = {
  FADE_IN_TIME: 1.5,
  FADE_OUT_TIME: 0.3,
  TIMER_WARNING_SECONDS: 15,
  MONAURAL_COMP: 0.7,
  COLOR_PARAM_TC: 0.06,
  NOISE_LP_FREQ: 1000,
  NOISE_LP_Q: 0.5,
};

export const UI = {
  STATIC_WAVE_POINTS: 220,
  STATIC_WAVE_CYCLES: 2.2,
};
